#ifndef CONFIG_H
#define CONFIG_H


#define DASHBOARD_INDICATOR_COUNT 5
#define FRONT_BLINKER_AMOUNT 3
#define BACK_BLINKER_AMOUNT 3
#define LED_AMOUNT DASHBOARD_INDICATOR_COUNT + FRONT_BLINKER_AMOUNT * 2 + BACK_BLINKER_AMOUNT * 2

#define LED_PIN 6
#define HIGH_BEAM_PIN 16

#define LEFT_BUTTON_PIN 3
#define CENTRAL_BUTTON_PIN 4
#define RIGHT_BUTTON_PIN 5


#endif